/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Stockfolio Financial Data API
 * A comprehensive financial data API powered by yfinance
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateClientRequest,
  CreateClientResponse,
  ErrorResponse,
  HTTPValidationError,
  TokenRequest,
  TokenResponse
} from '../financialDataApi.schemas';

import { useSendRequest } from '.././orvalSendRequest';




/**
 * Authenticate with client credentials and get JWT access token
 * @summary Get access token
 */
export const getTokenApiV1TokenPost = (
    tokenRequest: TokenRequest,
 signal?: AbortSignal
) => {
      
      
      return useSendRequest<TokenResponse>(
      {url: `/api/v1/token`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: tokenRequest, signal
    },
      );
    }
  


export const getGetTokenApiV1TokenPostMutationOptions = <TError = ErrorResponse | HTTPValidationError | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getTokenApiV1TokenPost>>, TError,{data: TokenRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof getTokenApiV1TokenPost>>, TError,{data: TokenRequest}, TContext> => {

const mutationKey = ['getTokenApiV1TokenPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getTokenApiV1TokenPost>>, {data: TokenRequest}> = (props) => {
          const {data} = props ?? {};

          return  getTokenApiV1TokenPost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type GetTokenApiV1TokenPostMutationResult = NonNullable<Awaited<ReturnType<typeof getTokenApiV1TokenPost>>>
    export type GetTokenApiV1TokenPostMutationBody = TokenRequest
    export type GetTokenApiV1TokenPostMutationError = ErrorResponse | HTTPValidationError | ErrorResponse

    /**
 * @summary Get access token
 */
export const useGetTokenApiV1TokenPost = <TError = ErrorResponse | HTTPValidationError | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getTokenApiV1TokenPost>>, TError,{data: TokenRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getTokenApiV1TokenPost>>,
        TError,
        {data: TokenRequest},
        TContext
      > => {

      const mutationOptions = getGetTokenApiV1TokenPostMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * Create a new client with generated credentials
 * @summary Create new client
 */
export const createClientApiV1ClientsPost = (
    createClientRequest: CreateClientRequest,
 signal?: AbortSignal
) => {
      
      
      return useSendRequest<CreateClientResponse | null>(
      {url: `/api/v1/clients`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createClientRequest, signal
    },
      );
    }
  


export const getCreateClientApiV1ClientsPostMutationOptions = <TError = HTTPValidationError | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createClientApiV1ClientsPost>>, TError,{data: CreateClientRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createClientApiV1ClientsPost>>, TError,{data: CreateClientRequest}, TContext> => {

const mutationKey = ['createClientApiV1ClientsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createClientApiV1ClientsPost>>, {data: CreateClientRequest}> = (props) => {
          const {data} = props ?? {};

          return  createClientApiV1ClientsPost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateClientApiV1ClientsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createClientApiV1ClientsPost>>>
    export type CreateClientApiV1ClientsPostMutationBody = CreateClientRequest
    export type CreateClientApiV1ClientsPostMutationError = HTTPValidationError | ErrorResponse

    /**
 * @summary Create new client
 */
export const useCreateClientApiV1ClientsPost = <TError = HTTPValidationError | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createClientApiV1ClientsPost>>, TError,{data: CreateClientRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createClientApiV1ClientsPost>>,
        TError,
        {data: CreateClientRequest},
        TContext
      > => {

      const mutationOptions = getCreateClientApiV1ClientsPostMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * Get information about the authenticated client
 * @summary Get current client info
 */
export const getCurrentClientApiV1ClientsMeGet = (
    
 signal?: AbortSignal
) => {
      
      
      return useSendRequest<unknown>(
      {url: `/api/v1/clients/me`, method: 'GET', signal
    },
      );
    }
  

export const getGetCurrentClientApiV1ClientsMeGetQueryKey = () => {
    return [`/api/v1/clients/me`] as const;
    }

    
export const getGetCurrentClientApiV1ClientsMeGetQueryOptions = <TData = Awaited<ReturnType<typeof getCurrentClientApiV1ClientsMeGet>>, TError = ErrorResponse | ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentClientApiV1ClientsMeGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCurrentClientApiV1ClientsMeGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCurrentClientApiV1ClientsMeGet>>> = ({ signal }) => getCurrentClientApiV1ClientsMeGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCurrentClientApiV1ClientsMeGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetCurrentClientApiV1ClientsMeGetQueryResult = NonNullable<Awaited<ReturnType<typeof getCurrentClientApiV1ClientsMeGet>>>
export type GetCurrentClientApiV1ClientsMeGetQueryError = ErrorResponse | ErrorResponse


export function useGetCurrentClientApiV1ClientsMeGet<TData = Awaited<ReturnType<typeof getCurrentClientApiV1ClientsMeGet>>, TError = ErrorResponse | ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentClientApiV1ClientsMeGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentClientApiV1ClientsMeGet>>,
          TError,
          Awaited<ReturnType<typeof getCurrentClientApiV1ClientsMeGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetCurrentClientApiV1ClientsMeGet<TData = Awaited<ReturnType<typeof getCurrentClientApiV1ClientsMeGet>>, TError = ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentClientApiV1ClientsMeGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentClientApiV1ClientsMeGet>>,
          TError,
          Awaited<ReturnType<typeof getCurrentClientApiV1ClientsMeGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetCurrentClientApiV1ClientsMeGet<TData = Awaited<ReturnType<typeof getCurrentClientApiV1ClientsMeGet>>, TError = ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentClientApiV1ClientsMeGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get current client info
 */

export function useGetCurrentClientApiV1ClientsMeGet<TData = Awaited<ReturnType<typeof getCurrentClientApiV1ClientsMeGet>>, TError = ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentClientApiV1ClientsMeGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetCurrentClientApiV1ClientsMeGetQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



