/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Stockfolio Financial Data API
 * A comprehensive financial data API powered by yfinance
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CompanyInfo,
  ErrorResponse,
  GetHistoricalDataApiV1StockTickerHistoryGetParams,
  HTTPValidationError,
  HistoricalDataResponse,
  PriceData,
  StockInfo
} from '../financialDataApi.schemas';

import { useSendRequest } from '.././orvalSendRequest';




/**
 * Get detailed information about a stock including price data and company information
 * @summary Get comprehensive stock information
 */
export const getStockInfoApiV1StockTickerGet = (
    ticker: string,
 signal?: AbortSignal
) => {
      
      
      return useSendRequest<StockInfo>(
      {url: `/api/v1/stock/${ticker}`, method: 'GET', signal
    },
      );
    }
  

export const getGetStockInfoApiV1StockTickerGetQueryKey = (ticker?: string,) => {
    return [`/api/v1/stock/${ticker}`] as const;
    }

    
export const getGetStockInfoApiV1StockTickerGetQueryOptions = <TData = Awaited<ReturnType<typeof getStockInfoApiV1StockTickerGet>>, TError = ErrorResponse | HTTPValidationError | ErrorResponse>(ticker: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStockInfoApiV1StockTickerGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStockInfoApiV1StockTickerGetQueryKey(ticker);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStockInfoApiV1StockTickerGet>>> = ({ signal }) => getStockInfoApiV1StockTickerGet(ticker, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(ticker), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStockInfoApiV1StockTickerGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetStockInfoApiV1StockTickerGetQueryResult = NonNullable<Awaited<ReturnType<typeof getStockInfoApiV1StockTickerGet>>>
export type GetStockInfoApiV1StockTickerGetQueryError = ErrorResponse | HTTPValidationError | ErrorResponse


export function useGetStockInfoApiV1StockTickerGet<TData = Awaited<ReturnType<typeof getStockInfoApiV1StockTickerGet>>, TError = ErrorResponse | HTTPValidationError | ErrorResponse>(
 ticker: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStockInfoApiV1StockTickerGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStockInfoApiV1StockTickerGet>>,
          TError,
          Awaited<ReturnType<typeof getStockInfoApiV1StockTickerGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetStockInfoApiV1StockTickerGet<TData = Awaited<ReturnType<typeof getStockInfoApiV1StockTickerGet>>, TError = ErrorResponse | HTTPValidationError | ErrorResponse>(
 ticker: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStockInfoApiV1StockTickerGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStockInfoApiV1StockTickerGet>>,
          TError,
          Awaited<ReturnType<typeof getStockInfoApiV1StockTickerGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetStockInfoApiV1StockTickerGet<TData = Awaited<ReturnType<typeof getStockInfoApiV1StockTickerGet>>, TError = ErrorResponse | HTTPValidationError | ErrorResponse>(
 ticker: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStockInfoApiV1StockTickerGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get comprehensive stock information
 */

export function useGetStockInfoApiV1StockTickerGet<TData = Awaited<ReturnType<typeof getStockInfoApiV1StockTickerGet>>, TError = ErrorResponse | HTTPValidationError | ErrorResponse>(
 ticker: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStockInfoApiV1StockTickerGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetStockInfoApiV1StockTickerGetQueryOptions(ticker,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Get current price information for a stock
 * @summary Get stock price data
 */
export const getStockPriceApiV1StockTickerPriceGet = (
    ticker: string,
 signal?: AbortSignal
) => {
      
      
      return useSendRequest<PriceData>(
      {url: `/api/v1/stock/${ticker}/price`, method: 'GET', signal
    },
      );
    }
  

export const getGetStockPriceApiV1StockTickerPriceGetQueryKey = (ticker?: string,) => {
    return [`/api/v1/stock/${ticker}/price`] as const;
    }

    
export const getGetStockPriceApiV1StockTickerPriceGetQueryOptions = <TData = Awaited<ReturnType<typeof getStockPriceApiV1StockTickerPriceGet>>, TError = ErrorResponse | HTTPValidationError | ErrorResponse>(ticker: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStockPriceApiV1StockTickerPriceGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStockPriceApiV1StockTickerPriceGetQueryKey(ticker);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStockPriceApiV1StockTickerPriceGet>>> = ({ signal }) => getStockPriceApiV1StockTickerPriceGet(ticker, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(ticker), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStockPriceApiV1StockTickerPriceGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetStockPriceApiV1StockTickerPriceGetQueryResult = NonNullable<Awaited<ReturnType<typeof getStockPriceApiV1StockTickerPriceGet>>>
export type GetStockPriceApiV1StockTickerPriceGetQueryError = ErrorResponse | HTTPValidationError | ErrorResponse


export function useGetStockPriceApiV1StockTickerPriceGet<TData = Awaited<ReturnType<typeof getStockPriceApiV1StockTickerPriceGet>>, TError = ErrorResponse | HTTPValidationError | ErrorResponse>(
 ticker: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStockPriceApiV1StockTickerPriceGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStockPriceApiV1StockTickerPriceGet>>,
          TError,
          Awaited<ReturnType<typeof getStockPriceApiV1StockTickerPriceGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetStockPriceApiV1StockTickerPriceGet<TData = Awaited<ReturnType<typeof getStockPriceApiV1StockTickerPriceGet>>, TError = ErrorResponse | HTTPValidationError | ErrorResponse>(
 ticker: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStockPriceApiV1StockTickerPriceGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStockPriceApiV1StockTickerPriceGet>>,
          TError,
          Awaited<ReturnType<typeof getStockPriceApiV1StockTickerPriceGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetStockPriceApiV1StockTickerPriceGet<TData = Awaited<ReturnType<typeof getStockPriceApiV1StockTickerPriceGet>>, TError = ErrorResponse | HTTPValidationError | ErrorResponse>(
 ticker: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStockPriceApiV1StockTickerPriceGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get stock price data
 */

export function useGetStockPriceApiV1StockTickerPriceGet<TData = Awaited<ReturnType<typeof getStockPriceApiV1StockTickerPriceGet>>, TError = ErrorResponse | HTTPValidationError | ErrorResponse>(
 ticker: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStockPriceApiV1StockTickerPriceGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetStockPriceApiV1StockTickerPriceGetQueryOptions(ticker,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Get current price information for multiple stocks. Returns a list of price data objects. If a ticker is invalid or fails, it will be omitted from the result.
 * @summary Get stock price data for multiple tickers
 */
export const getMultipleStockPricesApiV1StockTickersPricesGet = (
    tickers: string,
 signal?: AbortSignal
) => {
      
      
      return useSendRequest<PriceData[]>(
      {url: `/api/v1/stock/${tickers}/prices`, method: 'GET', signal
    },
      );
    }
  

export const getGetMultipleStockPricesApiV1StockTickersPricesGetQueryKey = (tickers?: string,) => {
    return [`/api/v1/stock/${tickers}/prices`] as const;
    }

    
export const getGetMultipleStockPricesApiV1StockTickersPricesGetQueryOptions = <TData = Awaited<ReturnType<typeof getMultipleStockPricesApiV1StockTickersPricesGet>>, TError = ErrorResponse | HTTPValidationError | ErrorResponse>(tickers: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMultipleStockPricesApiV1StockTickersPricesGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMultipleStockPricesApiV1StockTickersPricesGetQueryKey(tickers);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMultipleStockPricesApiV1StockTickersPricesGet>>> = ({ signal }) => getMultipleStockPricesApiV1StockTickersPricesGet(tickers, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(tickers), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMultipleStockPricesApiV1StockTickersPricesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetMultipleStockPricesApiV1StockTickersPricesGetQueryResult = NonNullable<Awaited<ReturnType<typeof getMultipleStockPricesApiV1StockTickersPricesGet>>>
export type GetMultipleStockPricesApiV1StockTickersPricesGetQueryError = ErrorResponse | HTTPValidationError | ErrorResponse


export function useGetMultipleStockPricesApiV1StockTickersPricesGet<TData = Awaited<ReturnType<typeof getMultipleStockPricesApiV1StockTickersPricesGet>>, TError = ErrorResponse | HTTPValidationError | ErrorResponse>(
 tickers: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMultipleStockPricesApiV1StockTickersPricesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMultipleStockPricesApiV1StockTickersPricesGet>>,
          TError,
          Awaited<ReturnType<typeof getMultipleStockPricesApiV1StockTickersPricesGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetMultipleStockPricesApiV1StockTickersPricesGet<TData = Awaited<ReturnType<typeof getMultipleStockPricesApiV1StockTickersPricesGet>>, TError = ErrorResponse | HTTPValidationError | ErrorResponse>(
 tickers: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMultipleStockPricesApiV1StockTickersPricesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMultipleStockPricesApiV1StockTickersPricesGet>>,
          TError,
          Awaited<ReturnType<typeof getMultipleStockPricesApiV1StockTickersPricesGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetMultipleStockPricesApiV1StockTickersPricesGet<TData = Awaited<ReturnType<typeof getMultipleStockPricesApiV1StockTickersPricesGet>>, TError = ErrorResponse | HTTPValidationError | ErrorResponse>(
 tickers: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMultipleStockPricesApiV1StockTickersPricesGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get stock price data for multiple tickers
 */

export function useGetMultipleStockPricesApiV1StockTickersPricesGet<TData = Awaited<ReturnType<typeof getMultipleStockPricesApiV1StockTickersPricesGet>>, TError = ErrorResponse | HTTPValidationError | ErrorResponse>(
 tickers: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMultipleStockPricesApiV1StockTickersPricesGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetMultipleStockPricesApiV1StockTickersPricesGetQueryOptions(tickers,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Get detailed company information for a stock
 * @summary Get company information
 */
export const getCompanyInfoApiV1StockTickerInfoGet = (
    ticker: string,
 signal?: AbortSignal
) => {
      
      
      return useSendRequest<CompanyInfo>(
      {url: `/api/v1/stock/${ticker}/info`, method: 'GET', signal
    },
      );
    }
  

export const getGetCompanyInfoApiV1StockTickerInfoGetQueryKey = (ticker?: string,) => {
    return [`/api/v1/stock/${ticker}/info`] as const;
    }

    
export const getGetCompanyInfoApiV1StockTickerInfoGetQueryOptions = <TData = Awaited<ReturnType<typeof getCompanyInfoApiV1StockTickerInfoGet>>, TError = ErrorResponse | HTTPValidationError | ErrorResponse>(ticker: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompanyInfoApiV1StockTickerInfoGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCompanyInfoApiV1StockTickerInfoGetQueryKey(ticker);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCompanyInfoApiV1StockTickerInfoGet>>> = ({ signal }) => getCompanyInfoApiV1StockTickerInfoGet(ticker, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(ticker), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCompanyInfoApiV1StockTickerInfoGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetCompanyInfoApiV1StockTickerInfoGetQueryResult = NonNullable<Awaited<ReturnType<typeof getCompanyInfoApiV1StockTickerInfoGet>>>
export type GetCompanyInfoApiV1StockTickerInfoGetQueryError = ErrorResponse | HTTPValidationError | ErrorResponse


export function useGetCompanyInfoApiV1StockTickerInfoGet<TData = Awaited<ReturnType<typeof getCompanyInfoApiV1StockTickerInfoGet>>, TError = ErrorResponse | HTTPValidationError | ErrorResponse>(
 ticker: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompanyInfoApiV1StockTickerInfoGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCompanyInfoApiV1StockTickerInfoGet>>,
          TError,
          Awaited<ReturnType<typeof getCompanyInfoApiV1StockTickerInfoGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetCompanyInfoApiV1StockTickerInfoGet<TData = Awaited<ReturnType<typeof getCompanyInfoApiV1StockTickerInfoGet>>, TError = ErrorResponse | HTTPValidationError | ErrorResponse>(
 ticker: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompanyInfoApiV1StockTickerInfoGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCompanyInfoApiV1StockTickerInfoGet>>,
          TError,
          Awaited<ReturnType<typeof getCompanyInfoApiV1StockTickerInfoGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetCompanyInfoApiV1StockTickerInfoGet<TData = Awaited<ReturnType<typeof getCompanyInfoApiV1StockTickerInfoGet>>, TError = ErrorResponse | HTTPValidationError | ErrorResponse>(
 ticker: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompanyInfoApiV1StockTickerInfoGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get company information
 */

export function useGetCompanyInfoApiV1StockTickerInfoGet<TData = Awaited<ReturnType<typeof getCompanyInfoApiV1StockTickerInfoGet>>, TError = ErrorResponse | HTTPValidationError | ErrorResponse>(
 ticker: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompanyInfoApiV1StockTickerInfoGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetCompanyInfoApiV1StockTickerInfoGetQueryOptions(ticker,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Get historical price data for a stock
 * @summary Get historical price data
 */
export const getHistoricalDataApiV1StockTickerHistoryGet = (
    ticker: string,
    params?: GetHistoricalDataApiV1StockTickerHistoryGetParams,
 signal?: AbortSignal
) => {
      
      
      return useSendRequest<HistoricalDataResponse>(
      {url: `/api/v1/stock/${ticker}/history`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetHistoricalDataApiV1StockTickerHistoryGetQueryKey = (ticker?: string,
    params?: GetHistoricalDataApiV1StockTickerHistoryGetParams,) => {
    return [`/api/v1/stock/${ticker}/history`, ...(params ? [params]: [])] as const;
    }

    
export const getGetHistoricalDataApiV1StockTickerHistoryGetQueryOptions = <TData = Awaited<ReturnType<typeof getHistoricalDataApiV1StockTickerHistoryGet>>, TError = ErrorResponse | ErrorResponse | HTTPValidationError | ErrorResponse>(ticker: string,
    params?: GetHistoricalDataApiV1StockTickerHistoryGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHistoricalDataApiV1StockTickerHistoryGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetHistoricalDataApiV1StockTickerHistoryGetQueryKey(ticker,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getHistoricalDataApiV1StockTickerHistoryGet>>> = ({ signal }) => getHistoricalDataApiV1StockTickerHistoryGet(ticker,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(ticker), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getHistoricalDataApiV1StockTickerHistoryGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetHistoricalDataApiV1StockTickerHistoryGetQueryResult = NonNullable<Awaited<ReturnType<typeof getHistoricalDataApiV1StockTickerHistoryGet>>>
export type GetHistoricalDataApiV1StockTickerHistoryGetQueryError = ErrorResponse | ErrorResponse | HTTPValidationError | ErrorResponse


export function useGetHistoricalDataApiV1StockTickerHistoryGet<TData = Awaited<ReturnType<typeof getHistoricalDataApiV1StockTickerHistoryGet>>, TError = ErrorResponse | ErrorResponse | HTTPValidationError | ErrorResponse>(
 ticker: string,
    params: undefined |  GetHistoricalDataApiV1StockTickerHistoryGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHistoricalDataApiV1StockTickerHistoryGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHistoricalDataApiV1StockTickerHistoryGet>>,
          TError,
          Awaited<ReturnType<typeof getHistoricalDataApiV1StockTickerHistoryGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetHistoricalDataApiV1StockTickerHistoryGet<TData = Awaited<ReturnType<typeof getHistoricalDataApiV1StockTickerHistoryGet>>, TError = ErrorResponse | ErrorResponse | HTTPValidationError | ErrorResponse>(
 ticker: string,
    params?: GetHistoricalDataApiV1StockTickerHistoryGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHistoricalDataApiV1StockTickerHistoryGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHistoricalDataApiV1StockTickerHistoryGet>>,
          TError,
          Awaited<ReturnType<typeof getHistoricalDataApiV1StockTickerHistoryGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetHistoricalDataApiV1StockTickerHistoryGet<TData = Awaited<ReturnType<typeof getHistoricalDataApiV1StockTickerHistoryGet>>, TError = ErrorResponse | ErrorResponse | HTTPValidationError | ErrorResponse>(
 ticker: string,
    params?: GetHistoricalDataApiV1StockTickerHistoryGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHistoricalDataApiV1StockTickerHistoryGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get historical price data
 */

export function useGetHistoricalDataApiV1StockTickerHistoryGet<TData = Awaited<ReturnType<typeof getHistoricalDataApiV1StockTickerHistoryGet>>, TError = ErrorResponse | ErrorResponse | HTTPValidationError | ErrorResponse>(
 ticker: string,
    params?: GetHistoricalDataApiV1StockTickerHistoryGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHistoricalDataApiV1StockTickerHistoryGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetHistoricalDataApiV1StockTickerHistoryGetQueryOptions(ticker,params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



