/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Stockfolio Financial Data API
 * A comprehensive financial data API powered by yfinance
 * OpenAPI spec version: 1.0.0
 */
/**
 * Business sector
 */
export type CompanyInfoSector = string | null;

/**
 * Industry
 */
export type CompanyInfoIndustry = string | null;

/**
 * Country of incorporation
 */
export type CompanyInfoCountry = string | null;

/**
 * Company website
 */
export type CompanyInfoWebsite = string | null;

/**
 * Company description
 */
export type CompanyInfoDescription = string | null;

/**
 * Number of employees
 */
export type CompanyInfoEmployees = number | null;

/**
 * Year founded
 */
export type CompanyInfoFounded = number | null;

/**
 * Schema for company information
 */
export interface CompanyInfo {
  /** Stock ticker symbol */
  symbol: string;
  /** Company name */
  name: string;
  /** Business sector */
  sector?: CompanyInfoSector;
  /** Industry */
  industry?: CompanyInfoIndustry;
  /** Country of incorporation */
  country?: CompanyInfoCountry;
  /** Company website */
  website?: CompanyInfoWebsite;
  /** Company description */
  description?: CompanyInfoDescription;
  /** Number of employees */
  employees?: CompanyInfoEmployees;
  /** Year founded */
  founded?: CompanyInfoFounded;
}

/**
 * Client description
 */
export type CreateClientRequestDescription = string | null;

/**
 * Schema for creating a new client
 */
export interface CreateClientRequest {
  /** Client name */
  name: string;
  /** Client description */
  description?: CreateClientRequestDescription;
}

/**
 * Client description
 */
export type CreateClientResponseDescription = string | null;

/**
 * Schema for client creation response
 */
export interface CreateClientResponse {
  /** Generated client ID */
  client_id: string;
  /** Generated client secret */
  client_secret: string;
  /** Client name */
  name: string;
  /** Client description */
  description?: CreateClientResponseDescription;
  /** Creation timestamp */
  created_at: string;
}

/**
 * Detailed error information
 */
export type ErrorResponseDetail = string | null;

/**
 * Schema for error responses
 */
export interface ErrorResponse {
  /** Error message */
  error: string;
  /** Detailed error information */
  detail?: ErrorResponseDetail;
  /** HTTP status code */
  status_code: number;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

/**
 * Schema for health check response
 */
export interface HealthCheck {
  /** Service status */
  status: string;
  /** API version */
  version: string;
  /** Current timestamp */
  timestamp: string;
}

/**
 * Opening price
 */
export type HistoricalDataPointOpen = number | null;

/**
 * Highest price
 */
export type HistoricalDataPointHigh = number | null;

/**
 * Lowest price
 */
export type HistoricalDataPointLow = number | null;

/**
 * Closing price
 */
export type HistoricalDataPointClose = number | null;

/**
 * Trading volume
 */
export type HistoricalDataPointVolume = number | null;

/**
 * Dividends paid
 */
export type HistoricalDataPointDividends = number | null;

/**
 * Stock splits
 */
export type HistoricalDataPointStockSplits = number | null;

/**
 * Schema for a single point of historical price data
 */
export interface HistoricalDataPoint {
  /** Date and time of the data point */
  date: string;
  /** Opening price */
  open?: HistoricalDataPointOpen;
  /** Highest price */
  high?: HistoricalDataPointHigh;
  /** Lowest price */
  low?: HistoricalDataPointLow;
  /** Closing price */
  close?: HistoricalDataPointClose;
  /** Trading volume */
  volume?: HistoricalDataPointVolume;
  /** Dividends paid */
  dividends?: HistoricalDataPointDividends;
  /** Stock splits */
  stock_splits?: HistoricalDataPointStockSplits;
}

/**
 * Schema for historical price data response
 */
export interface HistoricalDataResponse {
  /** Stock ticker symbol */
  symbol: string;
  /** Time period of the data */
  period: string;
  /** List of historical data points */
  data: HistoricalDataPoint[];
}

/**
 * Current price
 */
export type MarketDataPrice = number | null;

/**
 * Price change
 */
export type MarketDataChange = number | null;

/**
 * Price change percentage
 */
export type MarketDataChangePercent = number | null;

/**
 * Trading volume
 */
export type MarketDataVolume = number | null;

/**
 * Market capitalization
 */
export type MarketDataMarketCap = number | null;

/**
 * Price-to-earnings ratio
 */
export type MarketDataPeRatio = number | null;

/**
 * Schema for market data
 */
export interface MarketData {
  /** Stock ticker symbol */
  symbol: string;
  /** Company name */
  name: string;
  /** Current price */
  price?: MarketDataPrice;
  /** Price change */
  change?: MarketDataChange;
  /** Price change percentage */
  change_percent?: MarketDataChangePercent;
  /** Trading volume */
  volume?: MarketDataVolume;
  /** Market capitalization */
  market_cap?: MarketDataMarketCap;
  /** Price-to-earnings ratio */
  pe_ratio?: MarketDataPeRatio;
}

/**
 * Schema for market data response
 */
export interface MarketDataResponse {
  /** Top gainers */
  gainers: MarketData[];
  /** Top losers */
  losers: MarketData[];
  /** Most active stocks */
  active: MarketData[];
  /** Last update timestamp */
  last_updated: string;
}

/**
 * News publisher
 */
export type NewsArticlePublisher = string | null;

/**
 * URL to the full article
 */
export type NewsArticleLink = string | null;

/**
 * Publication date and time
 */
export type NewsArticlePublishedAt = string | null;

export type NewsArticleThumbnailAnyOf = { [key: string]: unknown };

/**
 * Thumbnail image information
 */
export type NewsArticleThumbnail = NewsArticleThumbnailAnyOf | null;

/**
 * Schema for news articles related to stocks
 */
export interface NewsArticle {
  /** Article title */
  title: string;
  /** News publisher */
  publisher?: NewsArticlePublisher;
  /** URL to the full article */
  link?: NewsArticleLink;
  /** Publication date and time */
  published_at?: NewsArticlePublishedAt;
  /** Thumbnail image information */
  thumbnail?: NewsArticleThumbnail;
  /** List of related ticker symbols */
  related_tickers?: string[];
}

/**
 * Current stock price
 */
export type PriceDataCurrentPrice = number | null;

/**
 * Previous closing price
 */
export type PriceDataPreviousClose = number | null;

/**
 * Opening price
 */
export type PriceDataOpen = number | null;

/**
 * Day's high
 */
export type PriceDataHigh = number | null;

/**
 * Day's low
 */
export type PriceDataLow = number | null;

/**
 * Trading volume
 */
export type PriceDataVolume = number | null;

/**
 * Market capitalization
 */
export type PriceDataMarketCap = number | null;

/**
 * Price-to-earnings ratio
 */
export type PriceDataPeRatio = number | null;

/**
 * Dividend yield
 */
export type PriceDataDividendYield = number | null;

/**
 * Price change
 */
export type PriceDataChange = number | null;

/**
 * Price change percentage
 */
export type PriceDataChangePercent = number | null;

/**
 * Last update timestamp
 */
export type PriceDataLastUpdated = string | null;

/**
 * Schema for stock price data
 */
export interface PriceData {
  /** Stock ticker symbol */
  symbol: string;
  /** Current stock price */
  current_price?: PriceDataCurrentPrice;
  /** Previous closing price */
  previous_close?: PriceDataPreviousClose;
  /** Opening price */
  open?: PriceDataOpen;
  /** Day's high */
  high?: PriceDataHigh;
  /** Day's low */
  low?: PriceDataLow;
  /** Trading volume */
  volume?: PriceDataVolume;
  /** Market capitalization */
  market_cap?: PriceDataMarketCap;
  /** Price-to-earnings ratio */
  pe_ratio?: PriceDataPeRatio;
  /** Dividend yield */
  dividend_yield?: PriceDataDividendYield;
  /** Price change */
  change?: PriceDataChange;
  /** Price change percentage */
  change_percent?: PriceDataChangePercent;
  /** Last update timestamp */
  last_updated?: PriceDataLastUpdated;
}

/**
 * Schema for search API response
 */
export interface SearchResponse {
  /** Search query */
  query: string;
  /** Search results */
  results: SearchResult[];
  /** Total number of results */
  total_count: number;
}

/**
 * Stock exchange
 */
export type SearchResultExchange = string | null;

/**
 * Instrument type
 */
export type SearchResultType = string | null;

/**
 * ISIN code
 */
export type SearchResultIsin = string | null;

/**
 * Country of listing
 */
export type SearchResultCountry = string | null;

/**
 * Schema for search results
 */
export interface SearchResult {
  /** Stock ticker symbol */
  symbol: string;
  /** Company name */
  name: string;
  /** Stock exchange */
  exchange?: SearchResultExchange;
  /** Instrument type */
  type?: SearchResultType;
  /** ISIN code */
  isin?: SearchResultIsin;
  /** Country of listing */
  country?: SearchResultCountry;
}

export type StockInfoAdditionalDataAnyOf = { [key: string]: unknown };

/**
 * Additional financial data
 */
export type StockInfoAdditionalData = StockInfoAdditionalDataAnyOf | null;

/**
 * Schema for comprehensive stock information
 */
export interface StockInfo {
  /** Stock ticker symbol */
  symbol: string;
  /** Current price information */
  price_data: PriceData;
  /** Company information */
  company_info: CompanyInfo;
  /** List of recent news articles */
  news?: NewsArticle[];
  /** Additional financial data */
  additional_data?: StockInfoAdditionalData;
}

/**
 * Schema for token request
 */
export interface TokenRequest {
  /** Client ID */
  client_id: string;
  /** Client Secret */
  client_secret: string;
}

/**
 * Schema for token response
 */
export interface TokenResponse {
  /** JWT access token */
  access_token: string;
  /** Token type */
  token_type?: string;
  /** Token expiration time in seconds */
  expires_in: number;
  /** Token expiration timestamp */
  expires_at: string;
}

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}

export type SearchInstrumentsApiV1SearchGetParams = {
/**
 * Search query (name, ISIN, or ticker symbol)
 * @minLength 2
 */
query: string;
/**
 * Maximum number of results to return
 * @minimum 1
 * @maximum 100
 */
limit?: number;
};

export type GetHistoricalDataApiV1StockTickerHistoryGetParams = {
/**
 * Time period (1d, 5d, 1mo, 3mo, 6mo, 1y, 2y, 5y, 10y, ytd, max)
 */
period?: string;
};

