/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Stockfolio Financial Data API
 * A comprehensive financial data API powered by yfinance
 * OpenAPI spec version: 1.0.0
 */
/**
 * Maximum number of news items per ticker
 */
export type BatchNewsRequestLimitPerTicker = number | null;

/**
 * Number of days to look back for news
 */
export type BatchNewsRequestDays = number | null;

/**
 * Schema for batch news request
 */
export interface BatchNewsRequest {
  /**
   * List of stock ticker symbols
   * @minItems 1
   * @maxItems 50
   */
  tickers: string[];
  /** Maximum number of news items per ticker */
  limit_per_ticker?: BatchNewsRequestLimitPerTicker;
  /** Number of days to look back for news */
  days?: BatchNewsRequestDays;
}

/**
 * Schema for batch news response
 */
export interface BatchNewsResponse {
  /** List of news by ticker */
  results: TickerNews[];
  /** Total number of articles returned */
  total_articles: number;
  /** Response timestamp */
  timestamp?: string;
}

/**
 * Business sector
 */
export type CompanyInfoSector = string | null;

/**
 * Industry
 */
export type CompanyInfoIndustry = string | null;

/**
 * Country of incorporation
 */
export type CompanyInfoCountry = string | null;

/**
 * Company website
 */
export type CompanyInfoWebsite = string | null;

/**
 * Company description
 */
export type CompanyInfoDescription = string | null;

/**
 * Number of employees
 */
export type CompanyInfoEmployees = number | null;

/**
 * Year founded
 */
export type CompanyInfoFounded = number | null;

/**
 * Schema for company information
 */
export interface CompanyInfo {
  /** Stock ticker symbol */
  symbol: string;
  /** Company name */
  name: string;
  /** Business sector */
  sector?: CompanyInfoSector;
  /** Industry */
  industry?: CompanyInfoIndustry;
  /** Country of incorporation */
  country?: CompanyInfoCountry;
  /** Company website */
  website?: CompanyInfoWebsite;
  /** Company description */
  description?: CompanyInfoDescription;
  /** Number of employees */
  employees?: CompanyInfoEmployees;
  /** Year founded */
  founded?: CompanyInfoFounded;
}

/**
 * Client description
 */
export type CreateClientRequestDescription = string | null;

/**
 * Schema for creating a new client
 */
export interface CreateClientRequest {
  /** Client name */
  name: string;
  /** Client description */
  description?: CreateClientRequestDescription;
}

/**
 * Client description
 */
export type CreateClientResponseDescription = string | null;

/**
 * Schema for client creation response
 */
export interface CreateClientResponse {
  /** Generated client ID */
  client_id: string;
  /** Generated client secret */
  client_secret: string;
  /** Client name */
  name: string;
  /** Client description */
  description?: CreateClientResponseDescription;
  /** Creation timestamp */
  created_at: string;
}

/**
 * The query that was executed (if custom query)
 */
export type EquityScreenResponseQuery = unknown | null;

/**
 * The predefined screener used (if predefined)
 */
export type EquityScreenResponseScreener = string | null;

/**
 * Schema for equity screening response
 */
export interface EquityScreenResponse {
  /** Total number of matching instruments */
  total: number;
  /** Number of instruments in this page */
  count: number;
  /** Current page number */
  page: number;
  /** Number of items per page */
  page_size: number;
  /** Total number of pages */
  total_pages: number;
  /** Matching instruments */
  results: SearchResult[];
  /** The query that was executed (if custom query) */
  query?: EquityScreenResponseQuery;
  /** The predefined screener used (if predefined) */
  screener?: EquityScreenResponseScreener;
}

/**
 * Detailed error information
 */
export type ErrorResponseDetail = string | null;

/**
 * Schema for error responses
 */
export interface ErrorResponse {
  /** Error message */
  error: string;
  /** Detailed error information */
  detail?: ErrorResponseDetail;
  /** HTTP status code */
  status_code: number;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

/**
 * Schema for health check response
 */
export interface HealthCheck {
  /** Service status */
  status: string;
  /** API version */
  version: string;
  /** Current timestamp */
  timestamp: string;
}

/**
 * Opening price
 */
export type HistoricalDataPointOpen = number | null;

/**
 * Highest price
 */
export type HistoricalDataPointHigh = number | null;

/**
 * Lowest price
 */
export type HistoricalDataPointLow = number | null;

/**
 * Closing price
 */
export type HistoricalDataPointClose = number | null;

/**
 * Trading volume
 */
export type HistoricalDataPointVolume = number | null;

/**
 * Dividends paid
 */
export type HistoricalDataPointDividends = number | null;

/**
 * Stock splits
 */
export type HistoricalDataPointStockSplits = number | null;

/**
 * Schema for a single point of historical price data
 */
export interface HistoricalDataPoint {
  /** Date and time of the data point */
  date: string;
  /** Opening price */
  open?: HistoricalDataPointOpen;
  /** Highest price */
  high?: HistoricalDataPointHigh;
  /** Lowest price */
  low?: HistoricalDataPointLow;
  /** Closing price */
  close?: HistoricalDataPointClose;
  /** Trading volume */
  volume?: HistoricalDataPointVolume;
  /** Dividends paid */
  dividends?: HistoricalDataPointDividends;
  /** Stock splits */
  stock_splits?: HistoricalDataPointStockSplits;
}

/**
 * Schema for historical price data response
 */
export interface HistoricalDataResponse {
  /** Stock ticker symbol */
  symbol: string;
  /** Time period of the data */
  period: string;
  /** List of historical data points */
  data: HistoricalDataPoint[];
}

/**
 * Current price
 */
export type MarketDataPrice = number | null;

/**
 * Price change
 */
export type MarketDataChange = number | null;

/**
 * Price change percentage
 */
export type MarketDataChangePercent = number | null;

/**
 * Trading volume
 */
export type MarketDataVolume = number | null;

/**
 * Market capitalization
 */
export type MarketDataMarketCap = number | null;

/**
 * Price-to-earnings ratio
 */
export type MarketDataPeRatio = number | null;

/**
 * Schema for market data
 */
export interface MarketData {
  /** Stock ticker symbol */
  symbol: string;
  /** Company name */
  name: string;
  /** Current price */
  price?: MarketDataPrice;
  /** Price change */
  change?: MarketDataChange;
  /** Price change percentage */
  change_percent?: MarketDataChangePercent;
  /** Trading volume */
  volume?: MarketDataVolume;
  /** Market capitalization */
  market_cap?: MarketDataMarketCap;
  /** Price-to-earnings ratio */
  pe_ratio?: MarketDataPeRatio;
}

/**
 * Schema for market data response
 */
export interface MarketDataResponse {
  /** Top gainers */
  gainers: MarketData[];
  /** Top losers */
  losers: MarketData[];
  /** Most active stocks */
  active: MarketData[];
  /** Last update timestamp */
  last_updated: string;
}

/**
 * Unique identifier for the article
 */
export type NewsArticleId = string | null;

/**
 * News publisher
 */
export type NewsArticlePublisher = string | null;

/**
 * URL to the full article
 */
export type NewsArticleLink = string | null;

/**
 * Publication date and time
 */
export type NewsArticlePublishedAt = string | null;

export type NewsArticleThumbnailAnyOf = { [key: string]: unknown };

/**
 * Thumbnail image information
 */
export type NewsArticleThumbnail = NewsArticleThumbnailAnyOf | null;

/**
 * Type of content (ARTICLE, VIDEO, etc.)
 */
export type NewsArticleContentType = string | null;

/**
 * Short summary of the article
 */
export type NewsArticleSummary = string | null;

/**
 * Full description or content preview
 */
export type NewsArticleDescription = string | null;

/**
 * Schema for news articles related to stocks
 */
export interface NewsArticle {
  /** Unique identifier for the article */
  id?: NewsArticleId;
  /** Article title */
  title: string;
  /** News publisher */
  publisher?: NewsArticlePublisher;
  /** URL to the full article */
  link?: NewsArticleLink;
  /** Publication date and time */
  published_at?: NewsArticlePublishedAt;
  /** Thumbnail image information */
  thumbnail?: NewsArticleThumbnail;
  /** List of related ticker symbols */
  related_tickers?: string[];
  /** Type of content (ARTICLE, VIDEO, etc.) */
  content_type?: NewsArticleContentType;
  /** Short summary of the article */
  summary?: NewsArticleSummary;
  /** Full description or content preview */
  description?: NewsArticleDescription;
  /** Whether the content is a video */
  is_video?: boolean;
}

/**
 * Predefined screener options
 */
export type PredefinedScreener = typeof PredefinedScreener[keyof typeof PredefinedScreener];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PredefinedScreener = {
  aggressive_small_caps: 'aggressive_small_caps',
  day_gainers: 'day_gainers',
  day_losers: 'day_losers',
  growth_technology_stocks: 'growth_technology_stocks',
  most_actives: 'most_actives',
  most_shorted_stocks: 'most_shorted_stocks',
  small_cap_gainers: 'small_cap_gainers',
  undervalued_growth_stocks: 'undervalued_growth_stocks',
  undervalued_large_caps: 'undervalued_large_caps',
  conservative_foreign_funds: 'conservative_foreign_funds',
  high_yield_bond: 'high_yield_bond',
  portfolio_anchors: 'portfolio_anchors',
  solid_large_growth_funds: 'solid_large_growth_funds',
  solid_midcap_growth_funds: 'solid_midcap_growth_funds',
  top_mutual_funds: 'top_mutual_funds',
} as const;

/**
 * Current stock price
 */
export type PriceDataCurrentPrice = number | null;

/**
 * Previous closing price
 */
export type PriceDataPreviousClose = number | null;

/**
 * Opening price
 */
export type PriceDataOpen = number | null;

/**
 * Day's high
 */
export type PriceDataHigh = number | null;

/**
 * Day's low
 */
export type PriceDataLow = number | null;

/**
 * Trading volume
 */
export type PriceDataVolume = number | null;

/**
 * Market capitalization
 */
export type PriceDataMarketCap = number | null;

/**
 * Price-to-earnings ratio
 */
export type PriceDataPeRatio = number | null;

/**
 * Dividend yield
 */
export type PriceDataDividendYield = number | null;

/**
 * Price change
 */
export type PriceDataChange = number | null;

/**
 * Price change percentage
 */
export type PriceDataChangePercent = number | null;

/**
 * Last update timestamp
 */
export type PriceDataLastUpdated = string | null;

/**
 * Schema for stock price data
 */
export interface PriceData {
  /** Stock ticker symbol */
  symbol: string;
  /** Current stock price */
  current_price?: PriceDataCurrentPrice;
  /** Previous closing price */
  previous_close?: PriceDataPreviousClose;
  /** Opening price */
  open?: PriceDataOpen;
  /** Day's high */
  high?: PriceDataHigh;
  /** Day's low */
  low?: PriceDataLow;
  /** Trading volume */
  volume?: PriceDataVolume;
  /** Market capitalization */
  market_cap?: PriceDataMarketCap;
  /** Price-to-earnings ratio */
  pe_ratio?: PriceDataPeRatio;
  /** Dividend yield */
  dividend_yield?: PriceDataDividendYield;
  /** Price change */
  change?: PriceDataChange;
  /** Price change percentage */
  change_percent?: PriceDataChangePercent;
  /** Last update timestamp */
  last_updated?: PriceDataLastUpdated;
}

/**
 * Schema for search API response
 */
export interface SearchResponse {
  /** Search query */
  query: string;
  /** Search results */
  results: SearchResult[];
  /** Total number of results */
  total_count: number;
}

/**
 * Stock exchange
 */
export type SearchResultExchange = string | null;

/**
 * Instrument type
 */
export type SearchResultType = string | null;

/**
 * Currency
 */
export type SearchResultCurrency = string | null;

/**
 * Country of listing
 */
export type SearchResultCountry = string | null;

/**
 * Current regular market price
 */
export type SearchResultRegularMarketPrice = number | null;

/**
 * Price change
 */
export type SearchResultRegularMarketChange = number | null;

/**
 * Price change percentage
 */
export type SearchResultRegularMarketChangePercent = number | null;

/**
 * Intraday price change
 */
export type SearchResultIntradayPriceChange = number | null;

/**
 * Bid price
 */
export type SearchResultBid = number | null;

/**
 * Ask price
 */
export type SearchResultAsk = number | null;

/**
 * 52-week high
 */
export type SearchResultFiftyTwoWeekHigh = number | null;

/**
 * 52-week low
 */
export type SearchResultFiftyTwoWeekLow = number | null;

/**
 * 52-week change percentage
 */
export type SearchResultFiftyTwoWeekChangePercent = number | null;

/**
 * Business sector
 */
export type SearchResultSector = string | null;

/**
 * Industry
 */
export type SearchResultIndustry = string | null;

/**
 * Market capitalization
 */
export type SearchResultMarketCap = number | null;

/**
 * Price-to-earnings ratio
 */
export type SearchResultPeRatio = number | null;

/**
 * Forward P/E ratio
 */
export type SearchResultForwardPe = number | null;

/**
 * Price-to-book ratio
 */
export type SearchResultPriceToBook = number | null;

/**
 * EPS (trailing 12 months)
 */
export type SearchResultEpsTrailingTwelveMonths = number | null;

/**
 * Forward EPS
 */
export type SearchResultEpsForward = number | null;

/**
 * EPS current year
 */
export type SearchResultEpsCurrentYear = number | null;

/**
 * Earnings growth rate
 */
export type SearchResultEarningsGrowth = number | null;

/**
 * Average analyst rating
 */
export type SearchResultAverageAnalystRating = string | null;

/**
 * Regular market volume
 */
export type SearchResultRegularMarketVolume = number | null;

/**
 * Average daily volume (3 months)
 */
export type SearchResultAverageDailyVolume3Month = number | null;

/**
 * Schema for search results
 */
export interface SearchResult {
  /** Stock ticker symbol */
  symbol: string;
  /** Company name */
  name: string;
  /** Stock exchange */
  exchange?: SearchResultExchange;
  /** Instrument type */
  type?: SearchResultType;
  /** Currency */
  currency?: SearchResultCurrency;
  /** Country of listing */
  country?: SearchResultCountry;
  /** Current regular market price */
  regular_market_price?: SearchResultRegularMarketPrice;
  /** Price change */
  regular_market_change?: SearchResultRegularMarketChange;
  /** Price change percentage */
  regular_market_change_percent?: SearchResultRegularMarketChangePercent;
  /** Intraday price change */
  intraday_price_change?: SearchResultIntradayPriceChange;
  /** Bid price */
  bid?: SearchResultBid;
  /** Ask price */
  ask?: SearchResultAsk;
  /** 52-week high */
  fifty_two_week_high?: SearchResultFiftyTwoWeekHigh;
  /** 52-week low */
  fifty_two_week_low?: SearchResultFiftyTwoWeekLow;
  /** 52-week change percentage */
  fifty_two_week_change_percent?: SearchResultFiftyTwoWeekChangePercent;
  /** Business sector */
  sector?: SearchResultSector;
  /** Industry */
  industry?: SearchResultIndustry;
  /** Market capitalization */
  market_cap?: SearchResultMarketCap;
  /** Price-to-earnings ratio */
  pe_ratio?: SearchResultPeRatio;
  /** Forward P/E ratio */
  forward_pe?: SearchResultForwardPe;
  /** Price-to-book ratio */
  price_to_book?: SearchResultPriceToBook;
  /** EPS (trailing 12 months) */
  eps_trailing_twelve_months?: SearchResultEpsTrailingTwelveMonths;
  /** Forward EPS */
  eps_forward?: SearchResultEpsForward;
  /** EPS current year */
  eps_current_year?: SearchResultEpsCurrentYear;
  /** Earnings growth rate */
  earnings_growth?: SearchResultEarningsGrowth;
  /** Average analyst rating */
  average_analyst_rating?: SearchResultAverageAnalystRating;
  /** Regular market volume */
  regular_market_volume?: SearchResultRegularMarketVolume;
  /** Average daily volume (3 months) */
  average_daily_volume_3_month?: SearchResultAverageDailyVolume3Month;
}

export type StockInfoAdditionalDataAnyOf = { [key: string]: unknown };

/**
 * Additional financial data
 */
export type StockInfoAdditionalData = StockInfoAdditionalDataAnyOf | null;

/**
 * Schema for comprehensive stock information
 */
export interface StockInfo {
  /** Stock ticker symbol */
  symbol: string;
  /** Current price information */
  price_data: PriceData;
  /** Company information */
  company_info: CompanyInfo;
  /** List of recent news articles */
  news?: NewsArticle[];
  /** Additional financial data */
  additional_data?: StockInfoAdditionalData;
}

/**
 * Schema for news related to a specific ticker
 */
export interface TickerNews {
  /** Stock ticker symbol */
  ticker: string;
  /** List of news articles */
  news: NewsArticle[];
}

/**
 * Schema for token request
 */
export interface TokenRequest {
  /** Client ID */
  client_id: string;
  /** Client Secret */
  client_secret: string;
}

/**
 * Schema for token response
 */
export interface TokenResponse {
  /** JWT access token */
  access_token: string;
  /** Token type */
  token_type?: string;
  /** Token expiration time in seconds */
  expires_in: number;
  /** Token expiration timestamp */
  expires_at: string;
}

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}

export type ScreenEquitiesApiV1ScreenPostParams = {
/**
 * Page number (1-indexed)
 * @minimum 1
 */
page?: number;
/**
 * Number of results per page
 * @minimum 1
 * @maximum 100
 */
page_size?: number;
};

export type ScreenEquitiesApiV1ScreenPostBody = { [key: string]: unknown };

export type ScreenPredefinedApiV1ScreenPredefinedScreenerNameGetParams = {
/**
 * Page number (1-indexed)
 * @minimum 1
 */
page?: number;
/**
 * Number of results per page
 * @minimum 1
 * @maximum 100
 */
page_size?: number;
};

export type SearchInstrumentsApiV1SearchGetParams = {
/**
 * Search query (name, ISIN, or ticker symbol)
 * @minLength 2
 */
query: string;
/**
 * Maximum number of results to return
 * @minimum 1
 * @maximum 100
 */
limit?: number;
};

export type GetHistoricalDataApiV1StockTickerHistoryGetParams = {
/**
 * Time period (1d, 5d, 1mo, 3mo, 6mo, 1y, 2y, 5y, 10y, ytd, max)
 */
period?: string;
};

