/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Stockfolio Financial Data API
 * A comprehensive financial data API powered by yfinance
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponse,
  HTTPValidationError,
  SearchInstrumentsApiV1SearchGetParams,
  SearchResponse,
  SearchResult
} from '../financialDataApi.schemas';

import { useSendRequest } from '.././orvalSendRequest';




/**
 * Search for stocks, ETFs, and other financial instruments by name, ISIN, or ticker symbol
 * @summary Search for financial instruments
 */
export const searchInstrumentsApiV1SearchGet = (
    params: SearchInstrumentsApiV1SearchGetParams,
 signal?: AbortSignal
) => {
      
      
      return useSendRequest<SearchResponse>(
      {url: `/api/v1/search`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getSearchInstrumentsApiV1SearchGetQueryKey = (params?: SearchInstrumentsApiV1SearchGetParams,) => {
    return [`/api/v1/search`, ...(params ? [params]: [])] as const;
    }

    
export const getSearchInstrumentsApiV1SearchGetQueryOptions = <TData = Awaited<ReturnType<typeof searchInstrumentsApiV1SearchGet>>, TError = ErrorResponse | HTTPValidationError | ErrorResponse>(params: SearchInstrumentsApiV1SearchGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchInstrumentsApiV1SearchGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchInstrumentsApiV1SearchGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchInstrumentsApiV1SearchGet>>> = ({ signal }) => searchInstrumentsApiV1SearchGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchInstrumentsApiV1SearchGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type SearchInstrumentsApiV1SearchGetQueryResult = NonNullable<Awaited<ReturnType<typeof searchInstrumentsApiV1SearchGet>>>
export type SearchInstrumentsApiV1SearchGetQueryError = ErrorResponse | HTTPValidationError | ErrorResponse


export function useSearchInstrumentsApiV1SearchGet<TData = Awaited<ReturnType<typeof searchInstrumentsApiV1SearchGet>>, TError = ErrorResponse | HTTPValidationError | ErrorResponse>(
 params: SearchInstrumentsApiV1SearchGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchInstrumentsApiV1SearchGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchInstrumentsApiV1SearchGet>>,
          TError,
          Awaited<ReturnType<typeof searchInstrumentsApiV1SearchGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useSearchInstrumentsApiV1SearchGet<TData = Awaited<ReturnType<typeof searchInstrumentsApiV1SearchGet>>, TError = ErrorResponse | HTTPValidationError | ErrorResponse>(
 params: SearchInstrumentsApiV1SearchGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchInstrumentsApiV1SearchGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchInstrumentsApiV1SearchGet>>,
          TError,
          Awaited<ReturnType<typeof searchInstrumentsApiV1SearchGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useSearchInstrumentsApiV1SearchGet<TData = Awaited<ReturnType<typeof searchInstrumentsApiV1SearchGet>>, TError = ErrorResponse | HTTPValidationError | ErrorResponse>(
 params: SearchInstrumentsApiV1SearchGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchInstrumentsApiV1SearchGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Search for financial instruments
 */

export function useSearchInstrumentsApiV1SearchGet<TData = Awaited<ReturnType<typeof searchInstrumentsApiV1SearchGet>>, TError = ErrorResponse | HTTPValidationError | ErrorResponse>(
 params: SearchInstrumentsApiV1SearchGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchInstrumentsApiV1SearchGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getSearchInstrumentsApiV1SearchGetQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Get a list of popular and widely traded stocks
 * @summary Get popular stocks
 */
export const getPopularStocksApiV1SearchPopularGet = (
    
 signal?: AbortSignal
) => {
      
      
      return useSendRequest<SearchResult[]>(
      {url: `/api/v1/search/popular`, method: 'GET', signal
    },
      );
    }
  

export const getGetPopularStocksApiV1SearchPopularGetQueryKey = () => {
    return [`/api/v1/search/popular`] as const;
    }

    
export const getGetPopularStocksApiV1SearchPopularGetQueryOptions = <TData = Awaited<ReturnType<typeof getPopularStocksApiV1SearchPopularGet>>, TError = ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPopularStocksApiV1SearchPopularGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPopularStocksApiV1SearchPopularGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPopularStocksApiV1SearchPopularGet>>> = ({ signal }) => getPopularStocksApiV1SearchPopularGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPopularStocksApiV1SearchPopularGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetPopularStocksApiV1SearchPopularGetQueryResult = NonNullable<Awaited<ReturnType<typeof getPopularStocksApiV1SearchPopularGet>>>
export type GetPopularStocksApiV1SearchPopularGetQueryError = ErrorResponse


export function useGetPopularStocksApiV1SearchPopularGet<TData = Awaited<ReturnType<typeof getPopularStocksApiV1SearchPopularGet>>, TError = ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPopularStocksApiV1SearchPopularGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPopularStocksApiV1SearchPopularGet>>,
          TError,
          Awaited<ReturnType<typeof getPopularStocksApiV1SearchPopularGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetPopularStocksApiV1SearchPopularGet<TData = Awaited<ReturnType<typeof getPopularStocksApiV1SearchPopularGet>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPopularStocksApiV1SearchPopularGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPopularStocksApiV1SearchPopularGet>>,
          TError,
          Awaited<ReturnType<typeof getPopularStocksApiV1SearchPopularGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetPopularStocksApiV1SearchPopularGet<TData = Awaited<ReturnType<typeof getPopularStocksApiV1SearchPopularGet>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPopularStocksApiV1SearchPopularGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get popular stocks
 */

export function useGetPopularStocksApiV1SearchPopularGet<TData = Awaited<ReturnType<typeof getPopularStocksApiV1SearchPopularGet>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPopularStocksApiV1SearchPopularGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetPopularStocksApiV1SearchPopularGetQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Search for a specific financial instrument by ISIN code
 * @summary Search by ISIN
 */
export const searchByIsinApiV1SearchIsinIsinGet = (
    isin: string,
 signal?: AbortSignal
) => {
      
      
      return useSendRequest<SearchResult>(
      {url: `/api/v1/search/isin/${isin}`, method: 'GET', signal
    },
      );
    }
  

export const getSearchByIsinApiV1SearchIsinIsinGetQueryKey = (isin?: string,) => {
    return [`/api/v1/search/isin/${isin}`] as const;
    }

    
export const getSearchByIsinApiV1SearchIsinIsinGetQueryOptions = <TData = Awaited<ReturnType<typeof searchByIsinApiV1SearchIsinIsinGet>>, TError = ErrorResponse | HTTPValidationError | ErrorResponse>(isin: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchByIsinApiV1SearchIsinIsinGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchByIsinApiV1SearchIsinIsinGetQueryKey(isin);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchByIsinApiV1SearchIsinIsinGet>>> = ({ signal }) => searchByIsinApiV1SearchIsinIsinGet(isin, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(isin), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchByIsinApiV1SearchIsinIsinGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type SearchByIsinApiV1SearchIsinIsinGetQueryResult = NonNullable<Awaited<ReturnType<typeof searchByIsinApiV1SearchIsinIsinGet>>>
export type SearchByIsinApiV1SearchIsinIsinGetQueryError = ErrorResponse | HTTPValidationError | ErrorResponse


export function useSearchByIsinApiV1SearchIsinIsinGet<TData = Awaited<ReturnType<typeof searchByIsinApiV1SearchIsinIsinGet>>, TError = ErrorResponse | HTTPValidationError | ErrorResponse>(
 isin: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchByIsinApiV1SearchIsinIsinGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchByIsinApiV1SearchIsinIsinGet>>,
          TError,
          Awaited<ReturnType<typeof searchByIsinApiV1SearchIsinIsinGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useSearchByIsinApiV1SearchIsinIsinGet<TData = Awaited<ReturnType<typeof searchByIsinApiV1SearchIsinIsinGet>>, TError = ErrorResponse | HTTPValidationError | ErrorResponse>(
 isin: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchByIsinApiV1SearchIsinIsinGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchByIsinApiV1SearchIsinIsinGet>>,
          TError,
          Awaited<ReturnType<typeof searchByIsinApiV1SearchIsinIsinGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useSearchByIsinApiV1SearchIsinIsinGet<TData = Awaited<ReturnType<typeof searchByIsinApiV1SearchIsinIsinGet>>, TError = ErrorResponse | HTTPValidationError | ErrorResponse>(
 isin: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchByIsinApiV1SearchIsinIsinGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Search by ISIN
 */

export function useSearchByIsinApiV1SearchIsinIsinGet<TData = Awaited<ReturnType<typeof searchByIsinApiV1SearchIsinIsinGet>>, TError = ErrorResponse | HTTPValidationError | ErrorResponse>(
 isin: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchByIsinApiV1SearchIsinIsinGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getSearchByIsinApiV1SearchIsinIsinGetQueryOptions(isin,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



