// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tonbljcxqunrriecgpup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvbmJsamN4cXVucnJpZWNncHVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMTQyNDksImV4cCI6MjA2OTg5MDI0OX0.WvhwhaYDrxHwNodfN0UsbxHrSdvzz1z7o7OTsRnRbYo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});